// Generated by CoffeeScript 1.6.3
(function() {
  describe("Raffler View Test", function() {
    var view;
    this.collection = view = void 0;
    beforeEach(function() {
      this.collection = new Raffler.Collections.Entries();
      this.collection.fetch();
      return view = new Raffler.Views.EntriesIndex({
        collection: this.collection
      });
    });
    it("should have create entries function defined", function() {
      return expect(view.newName).toBeDefined();
    });
    it("should have delete function defined", function() {
      return expect(view.delItem).toBeDefined();
    });
    it("should have render function defined", function() {
      return expect(view.render).toBeDefined();
    });
    it("should have initilaize function defined", function() {
      return expect(view.initialize).toBeDefined();
    });
    it("should have drawWinner function defined", function() {
      return expect(view.drawWinner).toBeDefined();
    });
    it("should have save model function defined", function() {
      return expect(view.saveModel).toBeDefined();
    });
    it("should have reset function defined", function() {
      return expect(view.reset).toBeDefined();
    });
    it("should have function to set model true", function() {
      return expect(view.setTrue).toBeDefined();
    });
    return it("should have function to set model false", function() {
      return expect(view.setFalse).toBeDefined();
    });
  });

}).call(this);
